# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58a5f7f693f34a62c0e148fd99ca1d553f6ed6e570b9895275d735e66995181d6dad61b9a18b3145d10971f5bb3eb78f47b566f4880409d8793c8930300d6a7c

test:
  secret_key_base: e963b1a3a811e0da4a859f3da7bb471b81cc423f6647a864644be3ec0799d26e696b4f27751e182b97bdc08579a8c7a84b4496a92942ce248c6f73e9401893b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
