# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 819ee8d2014bca109ef9353700eafc8d385a48410e25b4f8c877e0d1c7eb5da4e915cdaf881a883fc274e57820635cde58710789dd8cbd19fc95794c2680e5ce

test:
  secret_key_base: 7053b4c3e5e90fc90a48a5cb930bc4f88a127658e432be7222cce77a773bd420115315a28ec303abf76aab56977f15ffae0e40a0a2ba7a969a15c25f2adffccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
