# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a64b2ed5d3887ed6f7921f3d77fb32a10eb38da620d6e1d2922e3e2cf5efee65513681b88fdbd4e47c757e86ac4dcbde1640ba22d25d259444e530f35346f4

test:
  secret_key_base: 30ca352ee0c58d71c0eaaa75d2866b8e385692813bf4ff16d2c3f1ee7e34091ad362010bb52b529f29621c56b851daafb73774a60632f11d59e0cb11c90149b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
